server:
  port: 8081

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.56.26:3306/lease?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password: VectorX.123
    hikari:
      connection-test-query: SELECT 1 # 自动检测连接
      connection-timeout: 60000 #数据库连接超时时间,默认30秒
      idle-timeout: 500000 #空闲连接存活最大时间，默认600000（10分钟）
      max-lifetime: 540000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      maximum-pool-size: 12 #连接池最大连接数，默认是10
      minimum-idle: 10 #最小空闲连接数量
      pool-name: SPHHikariPool # 连接池名称
  jackson:
    time-zone: GMT+8
  # redis
  data:
    redis:
      host: 192.168.56.26
      port: 6379
      database: 0

#用于打印框架生成的sql语句，便于调试
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# json做打平处理，方便使用Knife4j调试
springdoc:
  default-flat-param-object: true

# 短信验证码
aliyun:
  sms:
    access-key-id: LTAI5tPh6Fe1J4DgzwbL4Wft
    access-key-secret: TkftWKy4h5PmmkT4MC6MDUhTC1z2xS
    endpoint: dysmsapi.aliyuncs.com
